import type { Metadata } from "next";
import localFont from "next/font/local";
import styles from "./layout.module.css";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";
import { CartProvider } from "@/context/cart-context";
import { CartIcon } from "./cart-icon";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <CartProvider>
          <nav className={styles.nav}>
            <div className={styles.home}>
              <h2 className={styles.header__title}>Shop</h2>
              <Link
                href="/"
                className={styles.icon}
                aria-label="Go to home page"
              >
                <Image
                  src="/svg/home.svg"
                  alt="cart-icon"
                  width={40}
                  height={40}
                />
              </Link>
            </div>
            <Link
              href="/cart"
              aria-label="Go to cart page"
              className={styles.icon}
            >
              <CartIcon />
            </Link>
          </nav>
          {children}
        </CartProvider>
      </body>
    </html>
  );
}
